version: "3.8"

services:
  frontend:
    build: ./frontend
    networks:
      - default
    restart: unless-stopped
    expose:
      - 80
    image: lenoreschedule_frontend:production
    container_name: lenoreschedule_frontend
    env_file:
      - ./.env
    environment:
      - TIMEZONE=America/New_York
      - TZ=${TIMEZONE}
  backend:
    build:
      context: ./backend
    command: /home/app/web/start.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - postgres_bkp:/backups/
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - default
      - backend
    env_file:
      - ./.env
    image: lenoreschedule_backend:production
    container_name: lenoreschedule_backend
  db:
    image: postgres:18-trixie
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - default
      - backend
    container_name: lenoreschedule_db
    environment:
      - TZ=UTC
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
  nginx:
    image: novanglus96/lenoreapps_proxy:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend
      - frontend
    networks:
      - default
    ports:
      - 7000:80
    container_name: lenoreschedule_proxy
    environment:
      - TZ=${TIMEZONE}

volumes:
  postgres_data:
  static_volume:
  media_volume:
  postgres_bkp:
   
networks:
  backend:
    internal: true